#!/bin/bash
flavour=debian
# use according mirror when building for Ubuntu
case "${distribution:-}" in
  bionic|xenial|trusty|precise)
    export MIRROR="http://archive.ubuntu.com/ubuntu/"
    flavour=ubuntu
    echo "*** Building for Ubuntu release ${distribution}, using mirror $MIRROR ***"
    ;;
  squeeze|wheezy)
    export MIRROR="http://archive.debian.org/debian/"
    echo "*** Building for Debian release ${distribution}, using mirror $MIRROR ***"
esac

if [ ${flavour} = ubuntu ] ; then
    export PIUPARTS_COMPONENTS=main,universe,restricted,multiverse
    echo "*** using components [${PIUPARTS_COMPONENTS}] ***"
fi

echo "*** flavour=${flavour} architecture=${architecture:-} ***"

# sadly piuparts always returns with exit code 1 :((
sudo piuparts_wrapper -D ${flavour} -d "${distribution}" \
    --ignore=/usr/bin/db_sql \
    --ignore=/usr/share/python/pyversions.pyc \
    "${PWD}"/artifacts/*.deb || true

if [ -f piuparts.txt ] ; then
    # generate TAP report
    piuparts_tap piuparts.txt > piuparts.tap
else
	echo "*** No piuparts.txt report ***"
	exit 1
fi
