#!/bin/bash
# Purpose: prepare setup and invoke Debian binary package build

# configuration for build-and-provide-package and its tools
export DEB_BUILD_OPTIONS="parallel=$(nproc)"
export BUILD_ONLY=true
export SUDO_CMD=sudo
export COWBUILDER_DIST=$distribution
export POST_BUILD_HOOK=/home/admin/kamailio-deb-jenkins/scripts/jdg-debc

# set specific mirror when building for Ubuntu
case "$distribution" in
  bionic|xenial|trusty|precise)
    export MIRRORSITE="http://archive.ubuntu.com/ubuntu/"
    echo "*** Building for Ubuntu release ${distribution}, using mirror $MIRRORSITE ***"
    ;;
  squeeze)
    export MIRRORSITE="http://archive.debian.org/debian/"
    echo "*** Building for Debian release ${distribution}, using mirror $MIRRORSITE ***"
    ;;
esac

# execute main jenkins-debian-glue script
/usr/bin/build-and-provide-package
