#!/bin/bash

export BASE_PATH="binaries/"
export PROVIDE_ONLY=true
export REPOSITORY="/srv/repository/${JOB_NAME%-repos*}"
export REPOS="${distribution}"
export SKIP_REMOVAL=true

/usr/bin/generate-reprepro-codename "${REPOS}"

# workaround reprepro not supporting ddeb packages
sed -i '/\.ddeb/d' binaries/*.changes

/usr/bin/build-and-provide-package
