#!/bin/bash
# Purpose: prepare setup and invoke Debian binary package build

# configuration for build-and-provide-package and its tools
DEB_BUILD_OPTIONS="parallel=$(nproc)"
export DEB_BUILD_OPTIONS
export BUILD_ONLY=true
export SUDO_CMD=sudo
# shellcheck disable=SC2154
export COWBUILDER_DIST=$distribution
export POST_BUILD_HOOK=/home/admin/kamailio-deb-jenkins/scripts/jdg-debc
export LINTIAN=true
export ADDITIONAL_BUILDRESULTS+=('../*lintian.txt')

if [ -n "${DEB_BUILD_PROFILES:-}" ]; then
  export DEB_BUILD_PROFILES="$DEB_BUILD_PROFILES"
  echo "*** DEB_BUILD_PROFILES=$DEB_BUILD_PROFILES ***"
else
  echo "*** DEB_BUILD_PROFILES is unset ***"
fi

# set specific mirror when building for Ubuntu
case "$distribution" in
  bionic|xenial|trusty|focal|jammy|noble)
    export MIRRORSITE="http://archive.ubuntu.com/ubuntu/"
    echo "*** Building for Ubuntu release ${distribution}, using mirror $MIRRORSITE ***"
    ;;
  precise)
    export MIRRORSITE="http://old-releases.ubuntu.com/ubuntu/"
    echo "*** Building for Ubuntu release ${distribution}, using mirror $MIRRORSITE ***"
    ;;
esac

# execute main jenkins-debian-glue script
/usr/bin/build-and-provide-package
